dist: bionic
language: cpp

sudo: required
services:
  - docker
script:
  - ./build-antara-gaming-sdk-docs.sh
  - docker build -t komodo_docs_image - < Vuepress.Dockerfile
  - docker run --rm -v $(pwd):/app/ -w /app/ -u $(id -u):$(id -g) -e ALGOLIAKEY=$ALGOLIAKEY komodo_docs_image
  - cd docs/.vuepress/dist/
#  - echo 'developers.komodoplatform.com' > CNAME
#  - cd -
#  - ./prepare-atomicDEX-docs.sh # modify the script to only run on master

deploy:
  #  - provider: pages
  #    skip-cleanup: true
  #    github-token: "$GH_TOKEN"
  #    local-dir: docs/.vuepress/dist/
  #    repo: komodoplatform/developer-docs
  #    on:
  #      branch: master
  #  - provider: pages
  #    skip-cleanup: true
  #    github-token: "$GH_TOKEN"
  #    local-dir: AtomicDEX-docs
  #    target_branch: master
  #    repo: komodoplatform/AtomicDEX-docs
  #    on:
  #      branch: master
  - provider: pages
    skip-cleanup: true
    github-token: "$GH_TOKEN"
    local-dir: docs/.vuepress/dist/
    target_branch: master
    repo: gcharang/gcharang.github.io
    on:
      branch: developer-docs-test

branches:
  only:
    - master
    - developer-docs-test
