version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Vuepress-dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app/
    container_name: komodo_docs
    user: "1000:1000"
